on:
  webhook:
    method: post
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          TOKEN: ${{ secrets.BLOG_WORKFLOW_DISPATCH_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/treten-reisen/blog/actions/workflows/astro.yml/dispatches \
            -d '{ "ref": "main" }'
